<?php

/**
 * @file
 * Contains bid.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\Node;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;
use Drupal\Core\Link;
use Drupal\Component\Serialization\Json;

/**
 * Implements hook_help().
 */
function bid_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bid module.
    case 'help.page.bid':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Bid features') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function bid_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'bid/bid';
}