<?php

/**
 * @file
 * Contains manage_content_relations.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\Node;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;
use Drupal\Core\Link;
use Drupal\Component\Serialization\Json;

/**
 * Implements hook_help().
 */
function manage_content_relations_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the manage_content_relations module.
    case 'help.page.manage_content_relations':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('manage_content_relations features') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function manage_content_relations_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'manage_content_relations/manage_content_relations';
}
?>